// Generated by Wrangler by running `wrangler types --env-interface Env`

interface Env {
	JWT_SECRET: string;
	WEBSOCKET_SERVER: DurableObjectNamespace<
		import("./src/index").WebSocketServer
	>;
	QUEUE: Queue;
}
declare module "*.sql" {
	const value: string;
	export default value;
}
